const marketList = [
  {
    id: '0',
    product: 'Server for web site',
    company: 'Sber Cloud',
    description: 'Docker container',
    success: 'ip address: 35.42.21.127:3030',
    trial: 'Your trial period ends in 30 days',
    cost: [190, 390, 790],
    type: 'docker',
  },
  {
    id: '1',
    product: 'Face recognition',
    company: 'Sber Cloud',
    success: 'Your license key: HGE4-LPF6-NBGF-12RR',
       trial: 'Your trial period ends in 30 days',
    description: 'License key',
    cost: [190, 390, 790],
    type: 'key',
  },
  {
    id: '2',
    product: 'Video Analytics',
    company: 'Sber Cloud',
    success: 'The usage period will end in 90 days',
       trial: 'Your trial period ends in 30 days',
    description: 'Subscription service',
    cost: [190, 390, 790],
    type: 'service',
  },
  {
    id: '3',
    product: 'Revenue analysis',
    company: 'Sber Cloud',
    success: 'The usage period will end in 90 days',
       trial: 'Your trial period ends in 30 days',
    description: 'Subscription service',
    cost: [190, 390, 790],
    type: 'service',
  },
  {
    id: '4',
    product: 'Cloud computing',
    company: 'Sber Cloud',
    description: 'Docker container',
    success: 'ip address: 35.42.21.127:3030',
       trial: 'Your trial period ends in 30 days',
    cost: [190, 390, 790],
    type: 'docker',
  },
  {
    id: '5',
    product: 'Validation algorithm',
    company: 'Sber Cloud',
    success: 'Your license key: HGE4-LPF6-NBGF-12RR',
       trial: 'Your trial period ends in 30 days',
    description: 'License key',
    cost: [190, 390, 790],
    type: 'key',
  },
  {
    id: '6',
    product: 'Useful software',
    company: 'Sber Cloud',
    success: 'Your license key: HGE4-LPF6-NBGF-12RR',
       trial: 'Your trial period ends in 30 days',
    description: 'License key',
    cost: [190, 390, 790],
    type: 'key',
  }
];
export default marketList;
