const marketList = [
  {
    id: '0',
    product: 'Сервер для сайта',
    company: 'Sber Cloud',
    description: 'Докер контейнер',
    success: 'ip address: 35.42.21.127:3030',
    trial: 'Ваш пробный период завершается через 30 дней',
    cost: [190, 390, 790],
    type: 'docker',
  },
  {
    id: '1',
    product: 'Распознавание лиц',
    company: 'Sber Cloud',
    success: 'Ваш лицензионный ключ: HGE4-LPF6-NBGF-12RR',
       trial: 'Ваш пробный период завершается через 30 дней',
    description: 'Лицензионный ключ',
    cost: [190, 390, 790],
    type: 'key',
  },
  {
    id: '2',
    product: 'Видеоаналитика',
    company: 'Sber Cloud',
    success: 'Период использования завершится через 90 дней',
       trial: 'Ваш пробный период завершается через 30 дней',
    description: 'Услуга по подписке',
    cost: [190, 390, 790],
    type: 'service',
  },
  {
    id: '3',
    product: 'Анализ выручки',
    company: 'Sber Cloud',
    success: 'Период использования завершится через 90 дней',
       trial: 'Ваш пробный период завершается через 30 дней',
    description: 'Услуга по подписке',
    cost: [190, 390, 790],
    type: 'service',
  },
  {
    id: '4',
    product: 'Облачные вычисления',
    company: 'Sber Cloud',
    description: 'Докер контейнер',
    success: 'ip address: 35.42.21.127:3030',
       trial: 'Ваш пробный период завершается через 30 дней',
    cost: [190, 390, 790],
    type: 'docker',
  },
  {
    id: '5',
    product: 'Алгоритм проверки',
    company: 'Sber Cloud',
    success: 'Ваш лицензионный ключ: HGE4-LPF6-NBGF-12RR',
       trial: 'Ваш пробный период завершается через 30 дней',
    description: 'Лицензионный ключ',
    cost: [190, 390, 790],
    type: 'key',
  },
  {
    id: '6',
    product: 'Полезное ПО',
    company: 'Sber Cloud',
    success: 'Ваш лицензионный ключ: HGE4-LPF6-NBGF-12RR',
       trial: 'Ваш пробный период завершается через 30 дней',
    description: 'Лицензионный ключ',
    cost: [190, 390, 790],
    type: 'key',
  }
];
export default marketList;
