const marketList = [
  {
    id: '0',
    product: 'huita',
    company: 'Рога и копыта',
    description: 'jkshdfkjak',
    cost1: 190,
    cost2: 390,
    cost3: 790,
    type: 'docker',
  },
  {
    id: '1',
    product: 'huita',
    company: 'Рога и копыта',
    description: 'jkshdfkjak',
    cost: '190',
    type: 'key',
  },
  {
    id: '2',
    product: 'huita',
    company: 'Рога и копыта',
    description: 'jkshdfkjak',
    cost: '190',
    type: 'service',
  },
  {
    id: '3',
    product: 'huita',
    company: 'Рога и копыта',
    description: 'jkshdfkjak',
    cost: '190',
    type: 'service',
  },
  {
    id: '4',
    product: 'huita',
    company: 'Рога и копыта',
    description: 'jkshdfkjak',
    cost: '190',
    type: 'docker',
  },
  {
    id: '5',
    product: 'huita',
    company: 'Рога и копыта',
    description: 'jkshdfkjak',
    cost: '190',
    type: 'key',
  },
  {
    id: '6',
    product: 'huita',
    company: 'Рога и копыта',
    description: 'jkshdfkjak',
    cost: '190',
    type: 'key',
  }
];
export default marketList;
